Update Mothership docs for change from a pair to a struct for hardware addressed packets
POETSII/orchestrator-documentation pull request #7
Opened 2021-02-02 13:30 UTC by heliosfa

This change updates the docs to reflect the changes that are being introduced on the Orchestrator's `FEATURE-0167-buffering_softswitch` branch.

Specifically, all instances of `std::pair<uint32_t, P_Pkt_t>` in the docs that relate to `PKTS` messages or their input/output method chains are replaced with `P_Addr_Pkt_t`

2021-02-12 12:20 UTC, mvousden commented
Just so you know, I'm holding off on the Orchestrator PR before this one.

2021-02-12 12:45 UTC, heliosfa commented
AS expected, hence why no review has been requested ;) I have another small update I need to make to these docs before I send it live for review as well.

2021-02-26 14:48 UTC, mvousden requested changes
This all looks fine to me, but I think either one of us should update the user guide with the Composer command set before we merge this all in :sweet_potato: .

2021-02-26 15:27 UTC, heliosfa commented
> This all looks fine to me, but I think either one of us should update the user guide with the Composer command set before we merge this all in 🍠 .

Agreed, it needs to be one big merge of everything to bring it all up to date!

2021-05-19 11:42 UTC, mvousden approved these changes
Top brass. Thank you!

2021-05-25 16:19 UTC, merged